version: "3.8"

services:
  db:
    image: postgres:14-alpine
    restart: always
    env_file: ./.env
    volumes:
      - boutique_hotel:/var/lib/psql

  web:
    build: ./web
    restart: always
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"

  server:
    build: ./server
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    stdin_open: true
    env_file: ./.env
    environment:
      - PORT=8080
      - DB_HOST=db

volumes:
  boutique_hotel:
