version: "3.8"

services:
  db:
    image: postgres:14-alpine
    restart: always
    env_file: ./.env
    volumes:
      - boutique_hotel:/var/lib/psql

  server:
    build: ./server
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    stdin_open: true
    env_file: ./.env
    environment:
      - DB_HOST=db
      - NODE_PORT=8080
      - DB_NAME=$POSTGRES_USER
      - DB_USERNAME=$POSTGRES_USER
      - DB_PASSWORD=$POSTGRES_PASSWORD

  web:
    build: ./web
    depends_on:
      - server
    restart: always
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"

  admin:
    build: ./admin
    depends_on:
      - server
    restart: always
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3001:3001"

volumes:
  boutique_hotel:
